### ISSUE TITLE
Error when no bet is provided to deal()

### ISSUE THREAD

**Issue by markbrouch** [kedoska/engine-blackjack#15]
### What kind of issue is this? "Bug" or "New Feature"
Bug

### Actual behavior
`Unexpected exception 'TypeError: Cannot read property 'bet' of undefined'`

### How can we reproduce it? From "Stage" -> "Action" -> Cards
```js
const game = new blackjack.Game();
game.dispatch(blackjack.actions.deal());
```

Error goes away by providing a bet value of 0 to `deal({ bet: 0 })`, but I think if `bet` is omitted it should automatically default 0 instead of throwing error.

**Comment by kedoska** [comment]
@markbrouch default value of `bet` was arbitrarily sets to `10` since the beginning.
Last [commit](https://github.com/kedoska/engine-blackjack/commit/48bb01323b1198d1ba374f4008d2063c8a1ec038) provides _better defaults_ but in real situations, when you are actually using the engine, passing values from the client, it should not be an issue.

This is off course a lack of documentation in this project...

**Comment by markbrouch** [comment]
@kedoska awesome thanks for the quick fix! I'm using the engine in a little blackjack training app that doesn't actually play a whole game so the betting doesn't matter much to me. I just passed an arbitrary value so it wouldn't error.
https://github.com/markbrouch/alexa-blackjack-trainer
