### ISSUE TITLE
What happened to the example?

### ISSUE THREAD

**Issue by 10thmtn** [kedoska/engine-blackjack#42]
You used to have an example basic ui, did that get obsoleted?

**Comment by kedoska** [comment]
Hi @10thmtn, indeed the example is not longer available due to last changes in insurance.

> When insurance is available after `deal`, `insurance` must be called with or without bet amount, so that `stage` and `payout` is updated according with user action.
> Also, insurance is now considered as a `sidebet` and not part of the general payout 

### Things I want to do 
 - publish this week a general purpose server (_express + helmet_) that can easily be used as starting point. It will be part of the README, not part of the _code_.
 - minimal example using `create-react-app`

Tell me if you have any preferences, i will consider that doing those pending tasks
