### ISSUE TITLE
Multiplayer Functionality. 

### ISSUE THREAD

**Issue by tyrellgordon** [kedoska/engine-blackjack#62]
### "New Feature" request 
Multiplayer

### Actual behavior

Hey there Kedoska, My name is Tyrell and I am working with AltspaceVR.  After looking through your repository we really liked what we saw and we would like to implement your your blackjack engine with our product.

In order to do so we need to add multiplayer functionality  to the engine but before we got started I wanted to ask if you had any thoughts on how to approach this endeavor.

**Comment by kedoska** [comment]
hey @tyrellgordon,

a multi-player blackjack is more about orchestration and transaction control.
The engine itself is not currently ready for multiple players but, implementing it should not be a pain (from the rules implementation point of view). I have implemented this in production in many places, however, the controller (till now) has been for single players only.

In order to implement a multi-player, one possible path could be:

1. make the game _multi_ (means supporting up to 3 or 5 or N _sits_);
2. be able to have a _single player_, playing on multiple _sits_, so that all the tests can be integrated;
3. implement the controller for the sits, this will be probably an external component (not part of the engine);
4. extend the controller to interface the external system balances;

**Comment by tyrellgordon** [comment]
Thanks for the swift response! Appreciated!

**Comment by nugaon** [comment]
Hey,
I made an engine which supports multiplayer and based on this project. I don't have the time to write tests to that but I have tested manually as I could. Feel free to make pull requests 
https://github.com/nugaon/blackjack-engine
